// <auto-generated />
namespace AdminPanel.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AtualizandoReferencias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtualizandoReferencias));
        
        string IMigrationMetadata.Id
        {
            get { return "201402230336228_AtualizandoReferencias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
